name: E2E API Tests Remotely

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  Chrome_Ubuntu_API_Test:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.4

      - name: Set up MySQL Server with Docker Containers
        run: docker compose -f src/main/resources/dockerFiles/docker-compose-mysql-v3.yml up -d

      - name: Set up Selenium Grid with Docker Containers
        run: docker compose -f src/main/resources/dockerFiles/docker-compose-grid-v3.yml up --scale chrome=6 --scale edge=0 --scale firefox=0 -d

      - name: Check Running Containers
        run: docker ps

      - name: Run tests
        continue-on-error: true
        run: >
          mvn clean test -Dtest="AddToCartTests.AddToCartWithSearchOnAPI,
          AddToCartTests.RemoveFromCartWithSearchOnAPI,
          CheckoutTests.CheckoutProductOnAPI,
          RegisterTests.RegisterNewUserOnAPI,
          SearchProductTests.SearchForProductOnAPI"
          -DexecutionType="Remote"
          -DbrowserType="Chrome"
          -DisHeadless="true"
          -DsyncWithDB="true"
          -DparallelMode="METHODS"
          -DthreadCount="6"

      - name: Generate Allure report
        run: mvn allure:report

      - name: Copy patch file to allure-maven-plugin folder
        run: cp src/main/resources/allow-file-access_open-report_chrome_windows.bat target/site/allure-maven-plugin

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: Allure Report API Tests Chrome Ubuntu
          path: "target/site/allure-maven-plugin"

      - name: Cleanup Docker Containers
        if: always()
        run: |
          docker compose -f src/main/resources/dockerFiles/docker-compose-grid-v3.yml down ; docker compose -f src/main/resources/dockerFiles/docker-compose-mysql-v3.yml down 
