name: E2E UI Tests Remotely

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  Chrome_Ubuntu_UI_Test:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.4

      - name: Set up MySQL Server with Docker Containers
        run: docker run --name dockerDB -p 3306:3306 -e MYSQL_ROOT_PASSWORD=yehia -d mysql && \sleep 10 && \docker cp src/test/resources/DBFiles/ProductsAndUsers.sql dockerDB:/ProductsAndUsers.sql && \docker exec -i dockerDB mysql -u root -p'yehia' -e "SOURCE /ProductsAndUsers.sql;"

      - name: Set up Selenium Grid with Docker Containers
        run: docker compose -f src/main/resources/docker-compose-mysql-v3.yml up -d

      - name: Check Running Containers
        run: docker ps

      - name: Run tests
        continue-on-error: true
        run: >
          mvn clean test -Dtest="AddToCartTests.AddToCartWithSearchOnGUI,
          CheckoutTests.CheckoutProductOnGUI,
          RegisterTests.RegisterNewUserOnGUI,
          SearchProductTests.SearchForProductOnGUI"
          -DexecutionType="Remote"
          -DbrowserType="Chrome"
          -DisHeadless="true"
          -DsyncWithDB="true"
          -D"allure.results.directory"="target/allure-results"

      - name: Generate Allure report
        run: mvn allure:report

      - name: Copy patch file to allure-maven-plugin folder
        run: cp src/main/resources/allow-file-access_open-report_chrome_windows.bat target/site/allure-maven-plugin

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: Allure Report UI Tests Chrome Ubuntu
          path: "target/site/allure-maven-plugin"

      - name: Cleanup Docker Containers
        if: always()
        run: |
          docker compose -f src/main/resources/docker-compose-grid-v3.yml down && docker compose -f src/main/resources/docker-compose-mysql-v3.yml down
