name: Test

on:
  workflow_dispatch:

jobs:
  Edge_Linux_Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.4

      - name: Run tests
        run: mvn clean test -Dtest="AddToCartTests.AddToCartWithSearchOnAPI" -DexecutionType="Local" -DsyncWithDB="false" -DbrowserType="Edge" -DisHeadless="true" -D"allure.results.directory"="target/allure-results"

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-edge
          path: target/allure-results

  Firefox_Linux_Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.4

      - name: Run tests
        run: mvn clean test -Dtest="SearchProductTests.SearchForProductOnAPI" -DexecutionType="Local" -DsyncWithDB="false" -DbrowserType="Firefox" -DisHeadless="true" -D"allure.results.directory"="target/allure-results"

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-firefox
          path: target/allure-results

  Combine_Allure_Reports:
    runs-on: ubuntu-latest
    needs: [Edge_Linux_Test, Firefox_Linux_Test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0

      - name: Install Allure
        run: |
          # Download and unzip Allure
          curl -o allure.zip -L "https://github.com/allure-framework/allure2/releases/latest/download/allure-2.30.0.zip"
          unzip allure.zip
          sudo mv allure-2.30.0 /opt/allure  # Move the whole directory
          echo "/opt/allure/bin" >> $GITHUB_PATH  # Add Allure to the PATH

      - name: Download Allure results from Edge
        uses: actions/download-artifact@v4
        with:
          name: allure-results-edge
          path: ./allure-results-edge

      - name: Download Allure results from Firefox
        uses: actions/download-artifact@v4
        with:
          name: allure-results-firefox
          path: ./allure-results-firefox

      - name: Combine Allure results
        run: |
          mkdir -p ./allure-results
          cp -r ./allure-results-edge/* ./allure-results/
          cp -r ./allure-results-firefox/* ./allure-results/

      - name: Generate Allure report
        run: allure generate ./allure-results --clean -o ./allure-report

      - name: Copy patch file to allure-maven-plugin folder
        run: cp src/main/resources/allow-file-access_open-report_chrome_windows.bat ./allure-report

      - name: Upload Combined Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: Combined_Allure_Report
          path: ./allure-report