name: Java Maven Selenium Tests

on:
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: yehia  # Updated password
          MYSQL_DATABASE: automationexercise
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=3

    env:
      DB_URL: jdbc:mysql://127.0.0.1:3306/automationexercise
      DB_USER: root
      DB_PASSWORD: yehia  # Updated password

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to be ready..."
          for i in {1..30}; do
            if mysqladmin ping -h 127.0.0.1 -uyehia --silent; then
              echo "MySQL is ready!"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Create Database Schema
        run: |
          echo "Creating database schema..."
          mysql -h 127.0.0.1 -u root -pyehia automationexercise <<EOF
          CREATE TABLE IF NOT EXISTS products (
              id INT AUTO_INCREMENT PRIMARY KEY,
              name VARCHAR(255) NOT NULL,
              price DECIMAL(10, 2) NOT NULL,
              description TEXT
          );
          EOF

      - name: Run tests
        run: mvn clean test -Dtest="YourTestClass" -DbrowserType="Chrome" -Ddb.url="${{ env.DB_URL }}" -Ddb.user="${{ env.DB_USER }}" -Ddb.password="${{ env.DB_PASSWORD }}"
