name: test1

on:
  workflow_dispatch:

jobs:
  run_test_1:
    runs-on: ubuntu-latest
    
    env:
      DB_URL: jdbc:mysql://127.0.0.1:3306/automationexercise
      DB_USER: root
      DB_PASSWORD: yehia
          
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0
        
      - name: Setup JDK 21
        uses: actions/setup-java@v4.4.0
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Run test
        run: mvn clean test -Dtest="LoginTests.LoginWithExistingUserOnGUI" -DbrowserType="Chrome"
