name: Test

on:
  workflow_dispatch:

jobs:
  Edge_Linux_Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.4

      - name: Install Allure
        run: |
          curl -o allure.zip -L "https://github.com/allure-framework/allure2/releases/latest/download/allure-2.30.0.zip"
          unzip allure.zip -d allure
          # Add to PATH
          echo "::add-path::$(pwd)/allure/allure-2.13.2/bin"

      - name: Run tests
        run: mvn clean test -Dtest="AddToCartTests.AddToCartWithSearchOnAPI" -DexecutionType="Local" -DsyncWithDB="false" -DbrowserType="Edge" -DisHeadless="true" -D"allure.results.directory"="target/allure-results"

      - name: Generate Allure report
        run: allure generate target/allure-results --clean --output target/site/allure-maven-plugin

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: Allure_Report_Edge_Linux
          path: "target/site/allure-maven-plugin"

  Firefox_Linux_Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.4

      - name: Install Allure
        run: |
          curl -o allure.zip -L "https://github.com/allure-framework/allure2/releases/latest/download/allure-2.30.0.zip"
          unzip allure.zip -d allure
          # Add to PATH
          echo "::add-path::$(pwd)/allure/allure-2.13.2/bin"

      - name: Run tests
        run: mvn clean test -Dtest="SearchProductTests.SearchForProductOnAPI" -DexecutionType="Local" -DsyncWithDB="false" -DbrowserType="Firefox" -DisHeadless="true" -D"allure.results.directory"="target/allure-results"

      - name: Generate Allure report
        run: allure generate target/allure-results --clean --output target/site/allure-maven-plugin

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: Allure_Report_Firefox_Linux
          path: "target/site/allure-maven-plugin"
