name: Test

on:
  workflow_dispatch:

jobs:
  Firefox_Ubuntu_Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.4

      - name: Run tests
        run: mvn clean test -Dtest="LinearTest"

      - name: List Surefire reports directory
        run: |
          echo "Listing contents of the Surefire reports directory:"
          ls -l target/surefire-reports

      - name: Upload Surefire reports
        uses: actions/upload-artifact@v2
        with:
          name: surefire-reports
          path: target/*
