name: Java Maven Selenium Tests

on:
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0
        if: always()
        continue-on-error: true
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          
      - name: Set up Selenium Grid with Docker Containers
        run: docker compose -f src/main/resources/docker-compose-v3.yml up --scale chrome=4 --scale edge=0 --scale firefox=0 -d
    
      - name: Check running containers
        run: docker ps
      - name: Run tests
        run: mvn clean test -Dtest="AddToCartTests.AddToCartWithSearchOnAPI" -DexecutionType="Remote" -DbrowserType="Chrome" -DisHeadless="true" -D"allure.results.directory"="target/allure-results"
        
      - name: Generate Allure report
        run: mvn allure:report
      - name: Copy patch file to allure-maven-plugin folder
        run: cp src/main/resources/allow-file-access_open-report_chrome_windows.bat target/site/allure-maven-plugin
      - name: Check files in the allure-maven-plugin folder
        run: ls target/site/allure-maven-plugin
      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: Allure Report
          path: "target/site/allure-maven-plugin"
