name: Test

on:
  workflow_dispatch:

jobs:
  Firefox_Ubuntu_Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.4

      - name: Run tests
        run: mvn clean test -Dtest="LinearTest"

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Firefox_Linux_Allure
          path: "allure-report/*_AllureReport.html"

      - name: Publish Test Results
        continue-on-error: true
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          check_name: "Tests Results Firefox_Linux"
          files: |
            target/surefire-reports/TEST-*.xml